# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMsg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000)),
                ('read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Disconnectedhooks',
            fields=[
                ('event', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'length less than two')])),
                ('category', models.CharField(choices=[('LL', 'League of Legends'), ('OW', 'Overwatch')], max_length=2)),
                ('description', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(2, 'length less than two')])),
                ('price', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1, 'minimum allowable $1'), django.core.validators.MaxValueValidator(500, 'more than max allowable price')])),
                ('photo', models.CharField(blank=True, max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('boughttimes', models.IntegerField(default=0)),
                ('sellmsg', models.TextField(blank=True, default='Please provide link to VOD', max_length=1000)),
                ('avgstars', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayname', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar', models.CharField(max_length=500)),
                ('about', models.TextField(max_length=2000)),
                ('slogan', models.CharField(max_length=500)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('avgstars', models.FloatField(blank=True, null=True)),
                ('buystars', models.FloatField(blank=True, null=True)),
                ('stripe', models.CharField(blank=True, max_length=50, null=True)),
                ('striperefresh', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OR', 'Purchased'), ('VS', 'VOD Received'), ('SS', 'Roast Delivered'), ('AC', 'Roast Accepted'), ('CO', 'Completed')], max_length=2)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.IntegerField(default=6)),
                ('photo', models.CharField(max_length=250)),
                ('stars', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Gig')),
            ],
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('LL', 'League of Legends'), ('OW', 'Overwatch')], max_length=2)),
                ('owusername', models.CharField(blank=True, max_length=64, null=True)),
                ('owrank', models.CharField(blank=True, choices=[('BR', 'Bronze'), ('SV', 'Silver'), ('GD', 'Gold'), ('PT', 'Platinum'), ('DI', 'Diamond'), ('MA', 'Master'), ('GM', 'Grandmaster'), ('UR', 'Unranked')], max_length=2, null=True)),
                ('lolusername', models.CharField(blank=True, max_length=64, null=True)),
                ('lolrank', models.CharField(blank=True, choices=[('BR', 'Bronze'), ('SV', 'Silver'), ('GD', 'Gold'), ('PT', 'Platinum'), ('DI', 'Diamond'), ('MA', 'Master'), ('CH', 'Challenger'), ('UR', 'Unranked')], max_length=2, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Purchase')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tempinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(blank=True, max_length=128, null=True)),
                ('zipcode', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Ranks'),
        ),
        migrations.AddField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Gig'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatentry',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sixerrapp.Purchase'),
        ),
        migrations.AddField(
            model_name='chatentry',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
