# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0004_auto_20170826_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='rank',
        ),
    ]
