# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0007_rankverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='taxamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
