# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 02:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0008_auto_20170902_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buystars',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
