# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0009_purchase_buystars'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vanitymail',
            field=models.CharField(default='replace.me@roast.gg', max_length=128),
        ),
    ]
