# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0010_profile_vanitymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emailverified',
            field=models.BooleanField(default=True),
        ),
    ]
