# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0011_profile_emailverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
